name: Output event details on issues
on: issues
jobs:
  event-details:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details on issues
        run: echo "hello ${{toJSON(github.event)}}"

