name: Output event details on issues
on:
  issues:
    types:
      - opened
    branches:
      - "03-practice-project"
jobs:
  event-details:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details on issues
        run: echo "hello ${{toJSON(github.event)}}"

